Task 13JavaScript в Rails.
Asdfif/TestGuru pull request #12
Opened 2021-02-16 09:42 UTC by Asdfif

Добавлена сортировка тестов по заголовку для обычных пользователей. Реализована проверка совпадения паролей при регистрации с помощью события  input.

2021-02-16 12:54 UTC, VidgarVii requested changes

2021-02-16 12:54 UTC, VidgarVii commented on app/javascript/utilities/confirmation.js
> +  var password = document.getElementById("user_password")
var deprecated
используй let/const

2021-02-16 12:54 UTC, VidgarVii commented on app/javascript/utilities/confirmation.js
> +  console.log('CHECKING PASSWORD')
отладочный код можно убирать

2021-02-16 12:54 UTC, VidgarVii commented on app/javascript/utilities/confirmation.js
> +  }
if (field) field.addEventListener('input', checkPasswordMatch)

2021-02-16 12:54 UTC, VidgarVii commented on app/javascript/utilities/confirmation.js
> +  var password = document.getElementById("user_password")
при каждом событии ищутся элементы. Лучше их мемоизировать выше и передавать аргументами в функцию

2021-02-16 12:54 UTC, VidgarVii commented on app/javascript/utilities/confirmation.js
> +}
if if else else вложенный снос башки когда знаешь ООП). JS кстати  ОО подходы поддерживает

2021-02-16 12:54 UTC, VidgarVii commented on app/javascript/packs/application.js
>  import 'utilities/sorting.js'
а где файл сортировки по заголовку?

2021-02-16 16:36 UTC, Asdfif commented on app/javascript/packs/application.js
>  import 'utilities/sorting.js'
Павел, вы мне сказали , что я не все выполнил. но вот ведь файл с сортировкой по заголовку для обычных пользователей.

https://github.com/Asdfif/TestGuru/blob/6a5e4dd380c7c22892605e8c02260e9012f69d41/app/views/tests/index.html.erb

utilities/sorting.js  и для админов и для обычных пользователей ведь работает, поэтому я просто поправил views/tests/index.html.erb

2021-02-17 06:32 UTC, VidgarVii commented on app/javascript/packs/application.js
>  import 'utilities/sorting.js'
эти файлы должны быть в ПР

2021-02-17 06:32 UTC, VidgarVii commented on app/javascript/utilities/confirmation.js
> +
так как переменные не будут переопределяться, то лучше использовать const

2021-02-17 14:23 UTC, merged